name: "gcnmamba"
phase: "train"
gpu_ids: [0]

path_cd:
  log: "logs"
  result: "results"
  checkpoint: "checkpoint"
  resume_state: null

datasets:
  train:
    name: "Dataset name"
    datasetroot: "Dataset root path"
    resolution: 256
    num_workers: 2
    batch_size: 1
    use_shuffle: true
    data_len: -1
  val:
    name: "Dataset name"
    datasetroot: "Dataset root path"
    resolution: 256
    num_workers: 2
    batch_size: 6
    use_shuffle: true
    data_len: -1
  test:
    name: "Dataset name"
    datasetroot: "Dataset root path"
    resolution: 256
    num_workers: 2
    batch_size: 6
    use_shuffle: false
    data_len: -1

model:
  name: "gcnmamba"
  loss: "ce_love"
  n_classes: 2
  stage: 2
  mamba_act: "relu"

train:
  n_epoch: 200
  train_print_iter: 500
  val_freq: 1
  val_print_iter: 50
  optimizer:
    type: "adam"
    lr: 0.0001
  sheduler:
    lr_policy: "linear"
    n_step: 3
    gamma: 0.1